### ISSUE TITLE
NED unpacking?

### ISSUE THREAD

**Issue by jabelk** [IvoP1/Ansible_NSO_Setup#1]
Might be worth including some logic to unpack or download NEDs too. You can see my ansible playbook logic doing that for the NSO Vagrant Ansible provisioning:
https://github.com/NSO-developer/nso-vagrant/blob/master/tasks/install_nso.yml#L51

**Comment by IvoP1** [comment]
Thanks Jason, i will take a look

Ivo

Jason Belk <notifications@github.com> escreveu no dia terça, 25/02/2020
à(s) 21:05:
